Merge pull request #1 from thompson-ele/master
thompson-ele/cosw30-fall2019 pull request #11
Opened 2019-10-23 04:26 UTC by safaaa01

Merge Update

2019-10-23 06:10 UTC, SavantLogics commented
Pull Request from Security

2019-10-23 19:43 UTC, thompson-ele commented on plp.html
> +<body>
This file should be a .php file and should be using the header and footer includes. Please remove this code and replace with the header include

2019-10-23 19:44 UTC, thompson-ele commented on plp.html
> +</div>
Instead of defining your own grid use the grid system that is found in our styleguide: http://treatstreet.herokuapp.com/styleguide/layout/

2019-10-23 19:45 UTC, thompson-ele commented on registration.php
> +    <div id="content-wrap">
Please remove these divs

2019-10-23 19:45 UTC, thompson-ele commented on registration.php
> +        <div class="container">
Please change this form a div to the `<main>` element

2019-10-23 19:46 UTC, thompson-ele commented on registration.php
> +                <label>First Name:</label><br>
For each `<label>` make sure to add the for attribute with the value set with the id of the input that it's connected to. For example this one would be: `<label for="first_name">`

2019-10-23 19:46 UTC, thompson-ele commented on plp.html
> +</html>
Please include the footer include here

2019-10-23 19:47 UTC, thompson-ele commented on login.php
> +    <div id="content-wrap">
Same with the registration page, you can remove these divs

2019-10-23 19:47 UTC, thompson-ele commented on login.php
> +            <div class="container">
Move the .container div outside of the <form> and change it to a `<main>` element for semantic reasons

2019-10-23 19:48 UTC, thompson-ele commented on login.php
> +                <input type="password" name="password" id="password" >
Is there a specific reason to not have this password input be sticky?

2019-10-23 19:49 UTC, thompson-ele commented on login.php
> +                <p>By creating an account you agree to our <a href="#" style="color:dodgerblue">Terms & Privacy</a>.</p>
Please remove all inline styles. If you need a color modifier you can use one of our utility classes but we'll be coming back and making modifications to this code so don't worry if it doesn't look 100% perfect: http://treatstreet.herokuapp.com/styleguide/utilities/

2019-10-23 19:49 UTC, thompson-ele commented on login.php
> +                    <button name="Cancel" class="cancelbutton">Cancel</button>
What happens when the user clicks on the Cancel button?

2019-10-23 19:50 UTC, thompson-ele commented on login.php
> +                    <button name="Login in" class="loginbutton">Log in!</button>
We don't need to add the name attribute to <button> elements. By wrapping a <button> with the <form> element, the <form> will pickup that if you click on it, to submit the form. Does this class do anything? If not, remove it please

2019-10-23 19:50 UTC, thompson-ele commented on login.php
> +                <div class="clearfix">
Does this class do anything? If not, remove it please

2019-10-23 19:51 UTC, thompson-ele requested changes
I've completed my first round review. Please make updates and commit your changes. Thanks!

2019-10-30 18:12 UTC, thompson-ele commented
@SavantLogics @safaaa01 is this ready to review again?

2019-11-05 03:58 UTC, thompson-ele approved these changes

2019-11-05 04:07 UTC, merged