Shopping Bag
thompson-ele/cosw30-fall2019 pull request #38
Opened 2019-11-25 23:43 UTC by rockondiana0416

I left the CSS for the shopping bag empty. I wasn't sure if I should do an import or includes. I would think an import. But the checkout is separate from the rest of the site. So I'm trying to wrap my head around styling it. I've looked at other websites and there is very little CSS. Then the checkout window is usually a pop up to the right side of the screen. Let me know what you think.

2019-11-27 04:20 UTC, thompson-ele commented
@rockondiana0416 So I think what you're thinking of is called a side rail. You'd have the products added to a small bag that popups out from the right hand side. To reduce complexity, I'd prefer if we have a dedicated shopping bag page. Something like Nordstrom's shopping bag where we have a list of products being purchased, followed by a total and button to continue the checkout process: https://secure.nordstrom.com/shopping-bag

This will allow us to do everything in PHP rather than having to use JavaScript which is not the focus of this class. I'm including a screenshot of an example I found on the interwebs that may be good for what we're doing:
<img width="977" alt="Screen Shot 2019-11-26 at 8 20 04 PM" src="https://user-images.githubusercontent.com/12629117/69693458-33deeb80-108a-11ea-8dde-8ae7894deb04.png">

Let me know if you have any other questions!

2019-11-27 04:22 UTC, thompson-ele requested changes
Make sure the shopping-bag.php file is outside of the model folder. For the shopping-bag.scss file I'd recommend moving it into the styleguide/modules folder and you would add an import in modules.scss so that the CSS you write in shopping-bag.scss gets compiled.

2019-11-27 04:22 UTC, thompson-ele commented on model/shopping-bag.php
> +<?php ?>
Please move this file out of the model folder :)

2019-12-04 04:42 UTC, rockondiana0416 commented
Hi Ele! Leo and I made changes to the shopping-bag. Patrick is taking a look at the css. Let me know what you think.

2019-12-05 02:22 UTC, thompson-ele approved these changes
Nice :)

2019-12-05 02:22 UTC, merged